"use server"

import { Genre, PopulateStoryType, Visibility } from "../defs";
import Story, { StoryType } from "../schemata/story";
import { PERFORM_DATABASE_ACTION } from "./types";

export async function storyFactory(quantity: number, authorId: string, genre?: Genre)
{
  const stories = [] as StoryType[]
  for ( let i = 1; i <= quantity; i++ )
  {
    stories.push({
      title: `Guest Story - ${i}`,
      content: `My epic story`,
      blurb: `Dummy story generated by debug panel`,
      genre: genre ?? Genre.NONE,
      userId: authorId,
      visibility: Visibility.PUBLIC,
    } as StoryType)
  }
  await PERFORM_DATABASE_ACTION(() => Story.insertMany(stories))
}

export async function populateStories(type: PopulateStoryType)
{
  switch(type)
  {
    case PopulateStoryType.GUEST:
      await storyFactory(5, "11037")
      break
    case PopulateStoryType.FIXED_GENRE:
      await storyFactory(10, "auth0|67e9d941c409585cbac8c6d7", Genre.DRAMA)
      break
  }
}