"use server"

import { Genre, PopulateActionType, Visibility } from "../defs";
import Story, { StoryType } from "../schemata/story";
import Rating from "../schemata/rating";
import Activity from "../schemata/activity";
import { getAllGenres, getAllRawGenres, randomChoiceFrom, randomStoryTitle } from "../utils";
import { PERFORM_DATABASE_ACTION } from "./types";

export async function storyFactory(quantity: number, authorId?: string | null, genre?: Genre)
{
  const stories = [] as StoryType[]
  for ( let i = 1; i <= quantity; i++ )
  {
    stories.push({
      title: `${randomStoryTitle()}`,
      content: `A story of a thousand words. Okay, well, maybe only like 500 tops.`,
      blurb: `Generated by the debug panel`,
      genre: genre ?? randomChoiceFrom(getAllRawGenres()),
      userId: authorId ?? randomChoiceFrom(["auth0|67f59baa8483e3889e5488d3", "auth0|67fae24b2659351f29407a8e", "auth0|67f51c7749b596a03a481431"]),
      visibility: Visibility.PUBLIC,
      metricsLastUpdated: new Date,
    } as StoryType)
  }
  await PERFORM_DATABASE_ACTION(() => Story.insertMany(stories))
}

export async function populateStories(type: PopulateActionType)
{
  switch(type)
  {
    case PopulateActionType.GUEST:
      await storyFactory(5, "11037")
      break
    case PopulateActionType.FIXED_GENRE:
      await storyFactory(10, "auth0|67e9d941c409585cbac8c6d7", randomChoiceFrom(getAllRawGenres()))
      break
    case PopulateActionType.RANDOM_GENRES:
      await storyFactory(20)
      break
      
      case PopulateActionType.DELETE_ALL_STORIES:
      await PERFORM_DATABASE_ACTION( () => Activity.deleteMany({}) )
      await PERFORM_DATABASE_ACTION( () => Rating.deleteMany({}) )
      await PERFORM_DATABASE_ACTION( () => Story.deleteMany({}) )
      break
    case PopulateActionType.DELETE_ALL_ACTIVITY:
      await PERFORM_DATABASE_ACTION( () => Activity.deleteMany({}) )
      break
    case PopulateActionType.DELETE_ALL_RATINGS:
      await PERFORM_DATABASE_ACTION( () => Activity.deleteMany({}) )
      await PERFORM_DATABASE_ACTION( () => Rating.deleteMany({}) )
      break

  }
}